<?php

declare(strict_types=1);

/**
 * Demo setup: package detail page, plugins, flexforms, route enhancer.
 * Run: docker exec typo3_web_1 php /app/packages/casablanca_booking/Scripts/setup-demo-package-pages.php
 */

use TYPO3\CMS\Core\Core\Bootstrap;
use TYPO3\CMS\Core\Core\SystemEnvironmentBuilder;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use Symfony\Component\Yaml\Yaml;

(static function (): void {
    $classLoader = require '/app/vendor/autoload.php';
    SystemEnvironmentBuilder::run(0, SystemEnvironmentBuilder::REQUESTTYPE_CLI);
    Bootstrap::init($classLoader);

    $pages = GeneralUtility::makeInstance(ConnectionPool::class)->getConnectionForTable('pages');
    $content = GeneralUtility::makeInstance(ConnectionPool::class)->getConnectionForTable('tt_content');
    $now = time();

    $detailPageUid = (int)($pages->fetchOne(
        'SELECT uid FROM pages WHERE deleted = 0 AND pid = 1 AND title = ? LIMIT 1',
        ['Package detail']
    ) ?: 0);

    if ($detailPageUid <= 0) {
        $pages->insert('pages', [
            'pid' => 1,
            'tstamp' => $now,
            'crdate' => $now,
            'title' => 'Package detail',
            'slug' => '/package-detail',
            'doktype' => 1,
        ]);
        $detailPageUid = (int)$pages->lastInsertId();
    }

    if ($detailPageUid <= 0) {
        fwrite(STDERR, "Failed to create detail page.\n");
        exit(1);
    }

    $detailFlexform = <<<'XML'
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>
        <sheet index="sDisplay">
            <language index="lDEF">
                <field index="settings.displayMode">
                    <value index="vDEF">detail</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
XML;

    $detailContentUid = (int)($content->fetchOne(
        'SELECT uid FROM tt_content WHERE deleted = 0 AND pid = ? AND CType = ? LIMIT 1',
        [$detailPageUid, 'casablancabooking_packages']
    ) ?: 0);

    if ($detailContentUid <= 0) {
        $content->insert('tt_content', [
            'pid' => $detailPageUid,
            'tstamp' => $now,
            'crdate' => $now,
            'CType' => 'casablancabooking_packages',
            'header' => 'Package detail',
            'pi_flexform' => $detailFlexform,
        ]);
    } else {
        $content->update('tt_content', ['pi_flexform' => $detailFlexform, 'tstamp' => $now], ['uid' => $detailContentUid]);
    }

    $overviewContentUid = (int)($content->fetchOne(
        'SELECT uid FROM tt_content WHERE deleted = 0 AND pid = 1 AND CType = ? ORDER BY sorting ASC LIMIT 1',
        ['casablancabooking_packages']
    ) ?: 0);

    if ($overviewContentUid > 0) {
        $overviewFlexform = <<<XML
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>
        <sheet index="sDisplay">
            <language index="lDEF">
                <field index="settings.displayMode">
                    <value index="vDEF">overview</value>
                </field>
                <field index="settings.cardLinkType">
                    <value index="vDEF">details</value>
                </field>
                <field index="settings.detailPageUid">
                    <value index="vDEF">{$detailPageUid}</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
XML;

        $content->update('tt_content', ['pi_flexform' => $overviewFlexform, 'tstamp' => $now], ['uid' => $overviewContentUid]);
    }

    $siteConfigPath = '/app/config/sites/autogenerated-1-c4ca4238a0b923820dcc509a6f75849b/config.yaml';
    if (is_readable($siteConfigPath)) {
        $config = Yaml::parseFile($siteConfigPath) ?? [];
        if (!isset($config['routeEnhancers'])) {
            $config['routeEnhancers'] = [];
        }

        $config['routeEnhancers']['CasablancaPackageDetail'] = [
            'type' => 'Extbase',
            'extension' => 'CasablancaBooking',
            'plugin' => 'Packages',
            'limitToPages' => [$detailPageUid],
            'routes' => [
                [
                    'routePath' => '/{packageSlug}',
                    '_controller' => 'Packages::show',
                    '_arguments' => [
                        'packageSlug' => 'packageSlug',
                    ],
                ],
            ],
            'defaultController' => 'Packages::show',
            'aspects' => [
                'packageSlug' => [
                    'type' => 'CasablancaPackageSlug',
                ],
            ],
        ];

        file_put_contents($siteConfigPath, Yaml::dump($config, 4, 2));
    }

    echo "detail_page_uid={$detailPageUid}\n";
    echo "overview_content_uid={$overviewContentUid}\n";
})();
